* Introduction
It's yet another custom Emacs configuration =) I hope, it will be the helpful
starting point for an Emacs beginner. All configuration files and options
are split into several different categories, for example, "appearance",
"edit", "search", "version control". Such approach helps to understand and
extend configuration more easily.
Also, there are two types of configuration files: setup files and customization
files. The first one contains information about package installation
and some basic configuration steps. And the second one contains more detailed
personal customizations for the package(s). It helps to leave the configuration
core unchanged but at the same time define new customizations for different
situations.
*  How To
** Learn Emacs
*** Useful links
+ [[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]] is a community driven list of useful Emacs packages,
  libraries and others.
+ [[https://www.gnu.org/software/emacs/manual/html_node/emacs/index.html][Emacs Manual]] is an official online manual.
+ [[https://www.emacswiki.org/][EmacsWiki]] is the collection of tutorials, source code, question and answers.
*** Useful articles
+ [[http://tuhdo.github.io/helm-intro.html][A Package in a league of its own: Helm.]]
+ [[http://tuhdo.github.io/helm-projectile.html][Exploring large projects with Projectile and Helm Projectile.]]
+ [[http://tuhdo.github.io/c-ide.html][C/C++ Development Environment for Emacs.]]
+ [[http://syamajala.github.io/c-ide.html][Emacs as C++ IDE.]]
* Installation
1. [required] Install [[https://www.gnu.org/software/emacs/][Emacs]].
   + I use versions 24.4 and 25.3.
   + Most GNU/Linux distributions provide GNU Emacs in their repositories.
     And installation process can be easy as 'sudo apt-get install emacs' =)
2. [required] Get configuration.
   + Just clone or download this repository to your Emacs directory:
     #+BEGIN_SRC sh
     git clone https://github.com/andron94/emacs-setup <Emacs directory>
     #+END_SRC
3. [optional] Install [[https://www.gnu.org/software/global/][GNU Global]]. It is used for source code navigation.
   + I also recommend to install [[http://pygments.org/][pygments]] plugin.
     It supports more languages out of the box than GNU Global.
   + To use it you should create/update gtags database in your project directory
     with next command:
     #+BEGIN_SRC sh
     gtags -c
     #+END_SRC
   + You can also create gtags database that is shared between all your
     projects. For example, you can create gtags for some commonly
     used libraries.
     + Set path to gtags database. Add it to '~/.profile'(or whatever you use).
       After that don't forget to reload '~/.profile' with 'source' command.
       #+BEGIN_SRC sh
       export GTAGSLIBPATH=<path to gtags database. For example, $HOME/.gtags/>
       #+END_SRC
     + Create the directory for such a database.
       #+BEGIN_SRC sh
       mkdir GTAGSLIBPATH
       #+END_SRC
     + Add external libraries/projects/code to gtags database directory.
       You can add more in the future.
       #+BEGIN_SRC sh
       cd GTAGSLIBPATH
       ln -s /LIBRARY PATH1/ LINK_NAME1
       ln -s /LIBRARY PATH2/ LINK_NAME2
       ln -s /LIBRARY PATH3/ LINK_NAME3
       ...
       #+END_SRC
     + Create/Update database.
       #+BEGIN_SRC sh
       cd GTAGSLIBPATH
       gtags -c
       #+END_SRC
4. [required] Run Emacs :) [[https://github.com/jwiegley/use-package][use-package]] will download and setup
   all packages automatically.
